### PR TITLE
Fix expired subscriptions reported as purchased

### PR DESCRIPTION
**Pull request by mlouli**
Good morning everyone! I just discovered this amazing library, big thanks to all contributors 👍

Now let me explain my changes: I noticed that whenever I purchase a subscription based product, it's reported as purchased even if the subscription has expired 😬

What do you think of my little changes ?

### CODE REVIEW

**Comment by benjaminmayo** [comment]
There is a leeway period (defined in the configuration) as the StoreKit system does not always refresh the expiry date instantly. This means subscriptions won't lapse instantly. I think the default is 30 days. I assume this is what you are seeing and there is no 'bug' to fix?

**Comment by mlouli** [comment]
My bad 😅, it's more clear for me right now, so that's why in sandbox environment expired subscriptions are always reported as purchased because they expires quickly (5 min for the monthly and 1 hour if I am not wrong for the yearly)

Do you think it worth a PR to handle this instead of hardcoding the 30 days value, or clients should on their side change it to fit their need ?

**Comment by benjaminmayo** [comment]
There's a testing configuration included with the framework which should invalidate instantly. Alternatively, you can make your own custom configuration for whatever build settings / testing needs you have.

**Comment by mlouli** [comment]
Yeah I saw the testing config but I cannot send a beta to apple with it, cause it's considered a release build. 

And using the default 30 days leeway period is a good thing on the released version of the app, but I am wondering if apple will reject my app when testing with a sandbox env, because every time they try to make a purchase of a subscription after they expires the app will tell them that the product has already been purchased

**Pull request closed without merging**
