### PR TITLE
Support for Subscription Offers

### PR DESCRIPTION
**Pull request by Prince2k3**
I added support for subscription offers. Based on how IntroductoryOffers is done, I used the same concepts for the offers discount

### CODE REVIEW

**Comment by Prince2k3** [comment]
Just a note.... I couldn't run the test for some reason. Xcode kepts throwing permission denied error. But I was able to run this in my own project without a problem. I wrote some of the tests around it still in hopes I can figure out why I can't run it in Xcode.

**Comment by benjaminmayo** [comment]
Regarding the tests, I believe sometimes you have to build the App Host target (select the scheme) first. Then, go back to the MerchantKit scheme and run the tests. I've had to battle with that before. 

Also on master, I'm currently adding support for macOS so maybe I broke something :P

**Comment by benjaminmayo** [comment]
Thanks for starting this pull request but it requires something a bit more holistic before I can merge it, like how a client can actually make a purchase applying the given discount. I have an idea here and I'll use your pull request as a springboard soon.

I also think we need to check whether the `SKProduct.discounts` array contains an item that represents the introductory offer, essentially duplicating the `introductoryPrice` discount. Last time I looked at the StoreKit documentation, this wasn't clear.

**Comment by Prince2k3** [comment]
Working on the tests fix. As far `discounts` the `introductoryOffer` is not included within the array. I verified that. Also I'm not seeing where the support for macOS is on master.

**Comment by benjaminmayo** [comment]
Awesome. Re macOS, oh woops, turns out I haven't pushed it yet. I have time allocated in the week to finish up on the macOS compatibility and attack the discount offers, so I greatly appreciate you doing the legwork here in this PR :)

**Comment by Prince2k3** [comment]
No problem! ..AND realized the promotional offers can't be used for new subscribers. Plus looks like there is a crazy signature thing that needs to happen first before it is applied to the user. Which would change how purchase is done for exisiting/previous subscribers

**Comment by benjaminmayo** [comment]
Sorry this took a little longer than I originally intended. I tweaked your PR to better match `MerchantKit` naming style. The discounts are exposed as `RetentionOffer` types. This structure includes the identifier so a future framework update can provide a way for the 'crazy signature stuff' to happen and actually apply a subscription promotional offer when committing a purchase.

**Comment by Prince2k3** [comment]
Awesome 👍🏿. I appreciate the look/updates into the PR. The library is very nice to use. I like your approach to managing StoreKit a lot.

**Pull request merged**
