### PR TITLE
SPM support

### PR DESCRIPTION
**Pull request by hallee**
I'm using SPM with Xcode 11 for a new project, and rather than add CocoaPods just for MerchantKit, I've done the bare minimum to get SPM working with this project.

Mostly just added missing imports. Also deleted an Obj-C header and replaced an Obj-C function with a Swift alternative.

Getting the test suite working with SPM would be a bit more work.

### CODE REVIEW

**Comment by benjaminmayo** [comment]
SPM doesn’t support resources so I had been deferring SPM support until that is available.

**Comment by hallee** [comment]
Feel free to close, I'll maintain my fork until then 👍

**Comment by benjaminmayo** [comment]
IIRC the resources are only used by the formatters so if we could exclude those files from the SPM product, until resources are supported, I’d be okay with that.

**Comment by hallee** [comment]
It seems SPM can pick up `*.stringsdict` files and the relevant tests pass! So, you may not need to wait for binary / file support.

I'll close this PR though as I've made some more aggressive changes and replaced your Xcodeproj.

**Pull request closed without merging**
