### PR TITLE
Draft: SPM Support

### PR DESCRIPTION
**Pull request by sgtsquiggs**
Hi,

This wasn't meant to be a production-ready pull request but it's the changes I made to get it working w/ SPM for myself.

I couldn't figure out how to get the header file to work w/ SPM - it complains that `priceLocaleFromProductDiscount` is undefined. Do get it compiling successfully I defined a placeholder in `Source/Model/Purchase.swift`.

I did have to import `Foundation` in every swift file where a Foundation type was referenced.

Hope this helps.

### CODE REVIEW

**Comment by benjaminmayo** [comment]
Thanks for doing this. I have some time again so I'm hoping to get SPM official soon.

**Comment by benjaminmayo** [comment]
Regarding the priceLocale shim, I'm just gonna drop pre iOS 12 support. Easiest path.

**Comment by benjaminmayo** [comment]
Hi @sgtsquiggs, can I kindly ask you try out the latest `master`? SPM should be working.

**Comment by sgtsquiggs** [comment]
It works targeting `master` - I think you'll need to tag a new release to get it working via version. Thanks!

**Comment by benjaminmayo** [comment]
Yea, I’ll tag and release as appropriate in the next few days.

**Pull request closed without merging**
